version: '3.9'

services:

    db:
      container_name: postgresql_db
      image: postgres
      restart: always
      expose:
        - "5433"
      ports:
        - "5433:5433"
      command: -p 5433
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres

    app:
      command: bash -c "python3 create_db.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      container_name: app
      build: .
      volumes:
        - .:/app
      environment:
        - DB_HOST=db
        - DB_PORT=5433
        - DB_PASSWORD=postgres
        - DB_NAME=postgres
        - DB_USER=postgres
      ports:
        - 8000:8000
      depends_on:
        - db
      restart: always

    
